# This workflow will publish a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '8.0.x']
    
    permissions:
      packages: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{matrix.dotnet-version}}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{matrix.dotnet-version}} # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Cubusky/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build the package
        run: dotnet build --configuration Release Cubusky.Core
      - name: Create the package
        run: dotnet pack --configuration Release Cubusky.Core
      - name: Publish the package to GPR
        run: dotnet nuget push Cubusky.Core/bin/Release/*.nupkg
