# This workflow will publish a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/Cubusky/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: dotnet build
        run: dotnet build -c Release -p:Version=${{ github.event.release.tag_name }} Cubusky.Core
      - name: dotnet pack
        run: dotnet pack -c Release -p:Version=${{ github.event.release.tag_name }} Cubusky.Core
      - name: dotnet nuget push
        run: dotnet nuget push Cubusky.Core/bin/Release/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}}
